export const catalog = [
  {
    id: "night-circus",
    title: "The Night Circus",
    author: "Erin Morgenstern",
    price: 8.49,
    format: "Paperback",
    availability: "In Stock",
    copies: 38,
    genres: ["fantasy", "literary"],
    signals: ["atmospheric", "romantic", "immersive", "character-driven", "slow-burn"],
    pace: "measured",
    synopsis:
      "A roaming circus becomes the stage for a secret competition wrapped in wonder and longing.",
    cover: {
      background: "linear-gradient(160deg, #121625 0%, #262b46 58%, #d6b970 100%)",
      accent: "#f4e0ac",
      text: "#fff6d7",
    },
  },
  {
    id: "project-hail-mary",
    title: "Project Hail Mary",
    author: "Andy Weir",
    price: 10.29,
    format: "Hardcover",
    availability: "In Stock",
    copies: 24,
    genres: ["science fiction", "adventure"],
    signals: ["page-turner", "witty", "big-idea", "hopeful", "character-driven"],
    pace: "fast",
    synopsis:
      "A lone astronaut wakes up with a mission that hinges on science, humor, and improvisation.",
    cover: {
      background: "linear-gradient(165deg, #081927 0%, #123c64 52%, #f59a57 100%)",
      accent: "#99dbff",
      text: "#f6fafc",
    },
  },
  {
    id: "lessons-in-chemistry",
    title: "Lessons in Chemistry",
    author: "Bonnie Garmus",
    price: 9.19,
    format: "Paperback",
    availability: "In Stock",
    copies: 31,
    genres: ["historical fiction", "literary"],
    signals: ["sharp", "witty", "character-driven", "uplifting", "voice-driven"],
    pace: "steady",
    synopsis:
      "An unconventional chemist reshapes her life and public voice with humor, intelligence, and resolve.",
    cover: {
      background: "linear-gradient(160deg, #18374b 0%, #40708b 50%, #f6cf7e 100%)",
      accent: "#fef1c6",
      text: "#fffdf5",
    },
  },
  {
    id: "seven-husbands",
    title: "The Seven Husbands of Evelyn Hugo",
    author: "Taylor Jenkins Reid",
    price: 7.69,
    format: "Paperback",
    availability: "In Stock",
    copies: 44,
    genres: ["historical fiction", "literary"],
    signals: ["glamorous", "character-driven", "page-turner", "emotionally-rich", "voice-driven"],
    pace: "fast",
    synopsis:
      "A Hollywood legend reveals the truth behind fame, ambition, and the relationships that defined her.",
    cover: {
      background: "linear-gradient(155deg, #13312b 0%, #26654f 45%, #d9b56d 100%)",
      accent: "#f7e0a5",
      text: "#fff8eb",
    },
  },
  {
    id: "thursday-murder-club",
    title: "The Thursday Murder Club",
    author: "Richard Osman",
    price: 8.99,
    format: "Paperback",
    availability: "In Stock",
    copies: 27,
    genres: ["mystery", "cozy fiction"],
    signals: ["witty", "ensemble", "cozy", "clever", "page-turner"],
    pace: "steady",
    synopsis:
      "A group of retirees turns amateur sleuthing into a delightfully sharp weekly habit.",
    cover: {
      background: "linear-gradient(150deg, #31251a 0%, #684936 52%, #d6c296 100%)",
      accent: "#f5e9cd",
      text: "#fffcf1",
    },
  },
  {
    id: "tomorrow-and-tomorrow",
    title: "Tomorrow, and Tomorrow, and Tomorrow",
    author: "Gabrielle Zevin",
    price: 11.49,
    format: "Paperback",
    availability: "In Stock",
    copies: 19,
    genres: ["literary", "contemporary fiction"],
    signals: ["character-driven", "ambitious", "friendship", "emotionally-rich", "thoughtful"],
    pace: "steady",
    synopsis:
      "A decades-long creative partnership examines friendship, ambition, and the cost of making things.",
    cover: {
      background: "linear-gradient(165deg, #241f44 0%, #47408a 54%, #f4c281 100%)",
      accent: "#eadbff",
      text: "#fff8eb",
    },
  },
  {
    id: "house-in-cerulean-sea",
    title: "The House in the Cerulean Sea",
    author: "TJ Klune",
    price: 9.49,
    format: "Paperback",
    availability: "In Stock",
    copies: 33,
    genres: ["fantasy", "cozy fiction"],
    signals: ["comforting", "whimsical", "found-family", "character-driven", "uplifting"],
    pace: "steady",
    synopsis:
      "A caseworker sent to a magical orphanage discovers warmth, belonging, and a gentler life.",
    cover: {
      background: "linear-gradient(160deg, #0d4662 0%, #278da8 54%, #f6da8f 100%)",
      accent: "#fcf3cf",
      text: "#fffef8",
    },
  },
  {
    id: "addie-larue",
    title: "The Invisible Life of Addie LaRue",
    author: "VE Schwab",
    price: 10.79,
    format: "Hardcover",
    availability: "In Stock",
    copies: 18,
    genres: ["fantasy", "literary"],
    signals: ["atmospheric", "romantic", "introspective", "slow-burn", "inventive"],
    pace: "measured",
    synopsis:
      "A woman makes a bargain to live forever, only to be forgotten by everyone she meets.",
    cover: {
      background: "linear-gradient(155deg, #171927 0%, #3d355a 52%, #c7a261 100%)",
      accent: "#f4ddad",
      text: "#fff8eb",
    },
  },
  {
    id: "remarkably-bright-creatures",
    title: "Remarkably Bright Creatures",
    author: "Shelby Van Pelt",
    price: 8.19,
    format: "Paperback",
    availability: "In Stock",
    copies: 22,
    genres: ["literary", "contemporary fiction"],
    signals: ["heartfelt", "quirky", "hopeful", "character-driven", "found-family"],
    pace: "steady",
    synopsis:
      "A widow, a teenager, and a clever octopus form an unexpected path toward connection and healing.",
    cover: {
      background: "linear-gradient(160deg, #0f3342 0%, #2e6f86 54%, #f3bc76 100%)",
      accent: "#f9edd1",
      text: "#fffdf8",
    },
  },
  {
    id: "silent-patient",
    title: "The Silent Patient",
    author: "Alex Michaelides",
    price: 7.29,
    format: "Paperback",
    availability: "Low Stock",
    copies: 4,
    genres: ["thriller", "mystery"],
    signals: ["page-turner", "twisty", "psychological", "fast-paced", "dark"],
    pace: "fast",
    synopsis:
      "A therapist becomes obsessed with uncovering why a famed painter stopped speaking after a murder.",
    cover: {
      background: "linear-gradient(155deg, #1a1a1a 0%, #414141 48%, #d7b07b 100%)",
      accent: "#edd7bb",
      text: "#fffdf8",
    },
  },
  {
    id: "daisy-jones",
    title: "Daisy Jones & The Six",
    author: "Taylor Jenkins Reid",
    price: 8.89,
    format: "Paperback",
    availability: "In Stock",
    copies: 21,
    genres: ["historical fiction", "contemporary fiction"],
    signals: ["voice-driven", "glamorous", "ensemble", "propulsive", "emotionally-rich"],
    pace: "fast",
    synopsis:
      "An oral history traces the meteoric rise and unraveling of a magnetic seventies rock band.",
    cover: {
      background: "linear-gradient(160deg, #302016 0%, #865134 52%, #f0bf7a 100%)",
      accent: "#ffe6c2",
      text: "#fff8ec",
    },
  },
  {
    id: "circe",
    title: "Circe",
    author: "Madeline Miller",
    price: 8.39,
    format: "Paperback",
    availability: "In Stock",
    copies: 17,
    genres: ["fantasy", "historical fiction"],
    signals: ["lyrical", "atmospheric", "mythic", "character-driven", "feminist"],
    pace: "measured",
    synopsis:
      "A banished witch claims her voice and power in a lush retelling rooted in Greek myth.",
    cover: {
      background: "linear-gradient(155deg, #2b1815 0%, #7b4631 55%, #e1bb76 100%)",
      accent: "#f9e7b4",
      text: "#fff8ef",
    },
  },
  {
    id: "klara-and-the-sun",
    title: "Klara and the Sun",
    author: "Kazuo Ishiguro",
    price: 9.99,
    format: "Hardcover",
    availability: "Limited Stock",
    copies: 6,
    genres: ["science fiction", "literary"],
    signals: ["thoughtful", "quiet", "emotional", "speculative", "character-driven"],
    pace: "measured",
    synopsis:
      "An artificial friend observes human longing, care, and fragility with unusual tenderness.",
    cover: {
      background: "linear-gradient(160deg, #202b2c 0%, #476666 52%, #efbf76 100%)",
      accent: "#fff0cf",
      text: "#fffdf6",
    },
  },
  {
    id: "yellowface",
    title: "Yellowface",
    author: "RF Kuang",
    price: 10.49,
    format: "Hardcover",
    availability: "Out of Stock",
    copies: 0,
    genres: ["thriller", "satire"],
    signals: ["sharp", "fast-paced", "darkly funny", "topical", "literary"],
    pace: "fast",
    synopsis:
      "A writer steals a manuscript and spirals into an increasingly public moral collapse.",
    cover: {
      background: "linear-gradient(160deg, #1b1f23 0%, #575d63 55%, #f2c54b 100%)",
      accent: "#fff0b6",
      text: "#fffdf5",
    },
  },
  {
    id: "demon-copperhead",
    title: "Demon Copperhead",
    author: "Barbara Kingsolver",
    price: 11.19,
    format: "Paperback",
    availability: "In Stock",
    copies: 14,
    genres: ["literary", "contemporary fiction"],
    signals: ["voice-driven", "immersive", "emotionally-rich", "propulsive", "resilient"],
    pace: "steady",
    synopsis:
      "A fiercely voiced coming-of-age story reframes a classic through rural Appalachia.",
    cover: {
      background: "linear-gradient(155deg, #2c1f19 0%, #6a4938 54%, #cfac6f 100%)",
      accent: "#faebc7",
      text: "#fff9ef",
    },
  },
  {
    id: "vanishing-half",
    title: "The Vanishing Half",
    author: "Brit Bennett",
    price: 8.69,
    format: "Paperback",
    availability: "In Stock",
    copies: 26,
    genres: ["historical fiction", "literary"],
    signals: ["character-driven", "layered", "ambitious", "identity", "emotionally-rich"],
    pace: "steady",
    synopsis:
      "Twin sisters choose radically different lives, and the ripple effects reach into the next generation.",
    cover: {
      background: "linear-gradient(165deg, #1c2333 0%, #48577d 50%, #e0b67c 100%)",
      accent: "#f3e6cf",
      text: "#fffaf1",
    },
  },
  {
    id: "song-of-achilles",
    title: "The Song of Achilles",
    author: "Madeline Miller",
    price: 8.09,
    format: "Paperback",
    availability: "Out of Stock",
    copies: 0,
    genres: ["fantasy", "historical fiction"],
    signals: ["romantic", "lyrical", "emotional", "mythic", "slow-burn"],
    pace: "measured",
    synopsis:
      "A mythic love story retells the Trojan War through intimacy, devotion, and heartbreak.",
    cover: {
      background: "linear-gradient(160deg, #1a1d2a 0%, #4d4269 48%, #d6aa6c 100%)",
      accent: "#f6dfb5",
      text: "#fffbf1",
    },
  },
  {
    id: "tom-lake",
    title: "Tom Lake",
    author: "Ann Patchett",
    price: 9.39,
    format: "Hardcover",
    availability: "In Stock",
    copies: 11,
    genres: ["literary", "contemporary fiction"],
    signals: ["reflective", "warm", "character-driven", "family", "elegant"],
    pace: "measured",
    synopsis:
      "A family revisits a mother’s youthful love story during a summer on their orchard.",
    cover: {
      background: "linear-gradient(160deg, #24311f 0%, #58704d 50%, #d9be84 100%)",
      accent: "#f6ebcf",
      text: "#fffef8",
    },
  },
  {
    id: "paris-apartment",
    title: "The Paris Apartment",
    author: "Lucy Foley",
    price: 7.79,
    format: "Paperback",
    availability: "In Stock",
    copies: 9,
    genres: ["thriller", "mystery"],
    signals: ["page-turner", "suspenseful", "ensemble", "atmospheric", "twisty"],
    pace: "fast",
    synopsis:
      "A glamorous Paris address hides resentments, secrets, and a disappearance no neighbor can explain.",
    cover: {
      background: "linear-gradient(160deg, #191e28 0%, #44526a 52%, #e1b37b 100%)",
      accent: "#efe0ca",
      text: "#fffdf6",
    },
  },
  {
    id: "wishing-game",
    title: "The Wishing Game",
    author: "Meg Shaffer",
    price: 8.29,
    format: "Paperback",
    availability: "In Stock",
    copies: 16,
    genres: ["fantasy", "contemporary fiction"],
    signals: ["whimsical", "heartfelt", "uplifting", "puzzle-like", "comforting"],
    pace: "steady",
    synopsis:
      "A reclusive author invites contestants to an island game where stories, hope, and chosen family intertwine.",
    cover: {
      background: "linear-gradient(165deg, #1d3145 0%, #4b6f8f 52%, #f0cc87 100%)",
      accent: "#fef2cf",
      text: "#fffdf7",
    },
  },
  {
    id: "piranesi",
    title: "Piranesi",
    author: "Susanna Clarke",
    price: 8.59,
    format: "Paperback",
    availability: "In Stock",
    copies: 12,
    genres: ["fantasy", "literary"],
    signals: ["atmospheric", "quiet", "inventive", "introspective", "character-driven"],
    pace: "measured",
    synopsis:
      "A man explores an endless house of tides, statues, and unsettling mysteries.",
    cover: {
      background: "linear-gradient(160deg, #1b2432 0%, #44546e 52%, #d9b37c 100%)",
      accent: "#f4dfbc",
      text: "#fffbf2",
    },
  },
  {
    id: "station-eleven",
    title: "Station Eleven",
    author: "Emily St. John Mandel",
    price: 8.89,
    format: "Paperback",
    availability: "In Stock",
    copies: 15,
    genres: ["science fiction", "literary"],
    signals: ["atmospheric", "hopeful", "character-driven", "ambitious", "reflective"],
    pace: "steady",
    synopsis:
      "An interconnected novel about art, survival, and human connection after a global collapse.",
    cover: {
      background: "linear-gradient(165deg, #102331 0%, #36566c 50%, #f0be7d 100%)",
      accent: "#f7e5c1",
      text: "#fffdf7",
    },
  },
  {
    id: "midnight-library",
    title: "The Midnight Library",
    author: "Matt Haig",
    price: 8.19,
    format: "Paperback",
    availability: "In Stock",
    copies: 28,
    genres: ["fantasy", "contemporary fiction"],
    signals: ["hopeful", "introspective", "inventive", "uplifting", "character-driven"],
    pace: "steady",
    synopsis:
      "A woman steps into a library between lives and explores what might have been.",
    cover: {
      background: "linear-gradient(155deg, #16203c 0%, #3f4a88 48%, #f0c46f 100%)",
      accent: "#f5e6bd",
      text: "#fffcf4",
    },
  },
  {
    id: "secret-history",
    title: "The Secret History",
    author: "Donna Tartt",
    price: 9.79,
    format: "Paperback",
    availability: "Limited Stock",
    copies: 7,
    genres: ["mystery", "literary"],
    signals: ["atmospheric", "dark", "voice-driven", "layered", "clever"],
    pace: "measured",
    synopsis:
      "A tightly wound campus novel of obsession, intellect, and a murder already in motion.",
    cover: {
      background: "linear-gradient(160deg, #1d1d20 0%, #444449 50%, #c8aa79 100%)",
      accent: "#ecd7b6",
      text: "#fffdf7",
    },
  },
  {
    id: "gentleman-in-moscow",
    title: "A Gentleman in Moscow",
    author: "Amor Towles",
    price: 9.89,
    format: "Paperback",
    availability: "In Stock",
    copies: 13,
    genres: ["historical fiction", "literary"],
    signals: ["elegant", "character-driven", "warm", "reflective", "thoughtful"],
    pace: "measured",
    synopsis:
      "A count lives under house arrest in a grand hotel and builds a life within its walls.",
    cover: {
      background: "linear-gradient(155deg, #23212e 0%, #5a5065 48%, #d6b47b 100%)",
      accent: "#f2dfbf",
      text: "#fffaf3",
    },
  },
  {
    id: "goldfinch",
    title: "The Goldfinch",
    author: "Donna Tartt",
    price: 10.49,
    format: "Paperback",
    availability: "Limited Stock",
    copies: 8,
    genres: ["literary", "contemporary fiction"],
    signals: ["immersive", "emotionally-rich", "voice-driven", "ambitious", "dark"],
    pace: "measured",
    synopsis:
      "A boy’s life splinters after tragedy, leading him through grief, art, and reinvention.",
    cover: {
      background: "linear-gradient(160deg, #20242d 0%, #5f6572 48%, #d7ba7f 100%)",
      accent: "#f3e4c8",
      text: "#fffdf8",
    },
  },
  {
    id: "cloud-cuckoo-land",
    title: "Cloud Cuckoo Land",
    author: "Anthony Doerr",
    price: 11.29,
    format: "Hardcover",
    availability: "In Stock",
    copies: 9,
    genres: ["historical fiction", "literary"],
    signals: ["ambitious", "hopeful", "inventive", "layered", "character-driven"],
    pace: "steady",
    synopsis:
      "A sweeping novel that links distant lives through books, imagination, and survival.",
    cover: {
      background: "linear-gradient(160deg, #173044 0%, #466988 52%, #e0be81 100%)",
      accent: "#f7e7c8",
      text: "#fffdf8",
    },
  },
  {
    id: "lincoln-highway",
    title: "The Lincoln Highway",
    author: "Amor Towles",
    price: 10.19,
    format: "Hardcover",
    availability: "In Stock",
    copies: 14,
    genres: ["historical fiction", "literary"],
    signals: ["voice-driven", "ensemble", "propulsive", "warm", "character-driven"],
    pace: "steady",
    synopsis:
      "A road novel about brothers, old debts, and the detours that reshape a family’s future.",
    cover: {
      background: "linear-gradient(155deg, #253127 0%, #566d4f 50%, #d5b177 100%)",
      accent: "#f5e4c3",
      text: "#fffdf6",
    },
  },
  {
    id: "sea-of-tranquility",
    title: "Sea of Tranquility",
    author: "Emily St. John Mandel",
    price: 9.69,
    format: "Hardcover",
    availability: "In Stock",
    copies: 11,
    genres: ["science fiction", "literary"],
    signals: ["thoughtful", "atmospheric", "speculative", "elegant", "emotional"],
    pace: "measured",
    synopsis:
      "Time, memory, and a strange anomaly connect lives across centuries.",
    cover: {
      background: "linear-gradient(160deg, #111d2a 0%, #35516d 50%, #e5bc7b 100%)",
      accent: "#f7e5c2",
      text: "#fffdf8",
    },
  },
  {
    id: "hamnet",
    title: "Hamnet",
    author: "Maggie O'Farrell",
    price: 8.79,
    format: "Paperback",
    availability: "In Stock",
    copies: 16,
    genres: ["historical fiction", "literary"],
    signals: ["lyrical", "emotional", "atmospheric", "character-driven", "reflective"],
    pace: "measured",
    synopsis:
      "A deeply felt novel imagining family grief in the shadow of Shakespeare’s household.",
    cover: {
      background: "linear-gradient(160deg, #2a1f21 0%, #6b4a4d 50%, #d9b67d 100%)",
      accent: "#f4e2c2",
      text: "#fffdf7",
    },
  },
  {
    id: "starless-sea",
    title: "The Starless Sea",
    author: "Erin Morgenstern",
    price: 10.99,
    format: "Hardcover",
    availability: "In Stock",
    copies: 10,
    genres: ["fantasy", "literary"],
    signals: ["atmospheric", "immersive", "slow-burn", "inventive", "romantic"],
    pace: "measured",
    synopsis:
      "A graduate student follows a mysterious book into a hidden world of stories within stories.",
    cover: {
      background: "linear-gradient(160deg, #141722 0%, #393e58 52%, #d3ad6f 100%)",
      accent: "#f2ddb1",
      text: "#fffbf3",
    },
  },
  {
    id: "dark-matter",
    title: "Dark Matter",
    author: "Blake Crouch",
    price: 8.49,
    format: "Paperback",
    availability: "In Stock",
    copies: 18,
    genres: ["science fiction", "thriller"],
    signals: ["page-turner", "big-idea", "fast-paced", "psychological", "twisty"],
    pace: "fast",
    synopsis:
      "A physicist is thrown into alternate realities and races to reclaim his life.",
    cover: {
      background: "linear-gradient(160deg, #121418 0%, #31404c 50%, #d0a86d 100%)",
      accent: "#efddc2",
      text: "#fffdf8",
    },
  },
  {
    id: "mexican-gothic",
    title: "Mexican Gothic",
    author: "Silvia Moreno-Garcia",
    price: 8.19,
    format: "Paperback",
    availability: "Low Stock",
    copies: 5,
    genres: ["mystery", "fantasy"],
    signals: ["atmospheric", "dark", "twisty", "page-turner", "inventive"],
    pace: "fast",
    synopsis:
      "A glamorous cousin arrives at a decaying estate and uncovers a sinister family history.",
    cover: {
      background: "linear-gradient(160deg, #20151c 0%, #5d3749 50%, #d0aa74 100%)",
      accent: "#f2dfc4",
      text: "#fffdf8",
    },
  },
  {
    id: "maid",
    title: "The Maid",
    author: "Nita Prose",
    price: 8.59,
    format: "Paperback",
    availability: "In Stock",
    copies: 17,
    genres: ["mystery", "cozy fiction"],
    signals: ["witty", "cozy", "character-driven", "clever", "page-turner"],
    pace: "steady",
    synopsis:
      "A hotel maid becomes the unexpected center of a murder investigation she sees differently than everyone else.",
    cover: {
      background: "linear-gradient(160deg, #21303b 0%, #557184 50%, #e3c086 100%)",
      accent: "#f6e6c9",
      text: "#fffdf8",
    },
  },
  {
    id: "malibu-rising",
    title: "Malibu Rising",
    author: "Taylor Jenkins Reid",
    price: 7.99,
    format: "Paperback",
    availability: "In Stock",
    copies: 21,
    genres: ["historical fiction", "contemporary fiction"],
    signals: ["glamorous", "ensemble", "emotionally-rich", "propulsive", "character-driven"],
    pace: "fast",
    synopsis:
      "Four famous siblings throw a party that unravels long-simmering family fault lines.",
    cover: {
      background: "linear-gradient(160deg, #163744 0%, #3e7b8f 52%, #efc278 100%)",
      accent: "#f9e7c8",
      text: "#fffdf8",
    },
  },
  {
    id: "carrie-soto-is-back",
    title: "Carrie Soto Is Back",
    author: "Taylor Jenkins Reid",
    price: 8.29,
    format: "Paperback",
    availability: "In Stock",
    copies: 19,
    genres: ["contemporary fiction", "historical fiction"],
    signals: ["propulsive", "voice-driven", "resilient", "character-driven", "sharp"],
    pace: "fast",
    synopsis:
      "A retired tennis legend returns for one more season to defend the record that made her famous.",
    cover: {
      background: "linear-gradient(160deg, #173444 0%, #3f6f85 50%, #f1c77e 100%)",
      accent: "#f9e8c7",
      text: "#fffdf8",
    },
  },
  {
    id: "anxious-people",
    title: "Anxious People",
    author: "Fredrik Backman",
    price: 8.49,
    format: "Paperback",
    availability: "In Stock",
    copies: 20,
    genres: ["contemporary fiction", "literary"],
    signals: ["witty", "heartfelt", "ensemble", "hopeful", "character-driven"],
    pace: "steady",
    synopsis:
      "A failed bank robbery becomes a warm, funny portrait of strangers forced together.",
    cover: {
      background: "linear-gradient(160deg, #1d3341 0%, #527280 50%, #e4bf81 100%)",
      accent: "#f6e6c8",
      text: "#fffdf8",
    },
  },
  {
    id: "babel",
    title: "Babel",
    author: "RF Kuang",
    price: 11.39,
    format: "Hardcover",
    availability: "In Stock",
    copies: 8,
    genres: ["fantasy", "historical fiction"],
    signals: ["ambitious", "topical", "character-driven", "immersive", "dark"],
    pace: "steady",
    synopsis:
      "Language, empire, and magic collide at Oxford in a sweeping historical fantasy.",
    cover: {
      background: "linear-gradient(160deg, #1d1d24 0%, #4a4f61 52%, #d8b06b 100%)",
      accent: "#f3ddb3",
      text: "#fffdf7",
    },
  },
  {
    id: "hello-beautiful",
    title: "Hello Beautiful",
    author: "Ann Napolitano",
    price: 10.29,
    format: "Hardcover",
    availability: "In Stock",
    copies: 12,
    genres: ["literary", "contemporary fiction"],
    signals: ["emotionally-rich", "character-driven", "family", "warm", "voice-driven"],
    pace: "steady",
    synopsis:
      "A family saga about love, ambition, and the ties that survive even deep fracture.",
    cover: {
      background: "linear-gradient(160deg, #2a2536 0%, #665b79 50%, #d8b583 100%)",
      accent: "#f3e4c9",
      text: "#fffdf8",
    },
  },
  {
    id: "covenant-of-water",
    title: "The Covenant of Water",
    author: "Abraham Verghese",
    price: 12.19,
    format: "Hardcover",
    availability: "Limited Stock",
    copies: 5,
    genres: ["historical fiction", "literary"],
    signals: ["immersive", "ambitious", "family", "emotionally-rich", "reflective"],
    pace: "measured",
    synopsis:
      "A sweeping family epic set in Kerala, shaped by medicine, inheritance, and loss.",
    cover: {
      background: "linear-gradient(160deg, #183041 0%, #456c83 50%, #ddb97f 100%)",
      accent: "#f6e6c8",
      text: "#fffdf8",
    },
  },
  {
    id: "measure",
    title: "The Measure",
    author: "Nikki Erlick",
    price: 9.49,
    format: "Hardcover",
    availability: "In Stock",
    copies: 13,
    genres: ["science fiction", "contemporary fiction"],
    signals: ["big-idea", "character-driven", "thoughtful", "emotionally-rich", "hopeful"],
    pace: "steady",
    synopsis:
      "A speculative novel about what happens when everyone learns the length of their life.",
    cover: {
      background: "linear-gradient(160deg, #1d2233 0%, #4b577a 50%, #dfbb7f 100%)",
      accent: "#f5e6c9",
      text: "#fffdf8",
    },
  },
  {
    id: "dutch-house",
    title: "The Dutch House",
    author: "Ann Patchett",
    price: 8.99,
    format: "Paperback",
    availability: "In Stock",
    copies: 16,
    genres: ["literary", "contemporary fiction"],
    signals: ["voice-driven", "family", "reflective", "elegant", "character-driven"],
    pace: "measured",
    synopsis:
      "A brother and sister spend decades circling the house that defined their childhood.",
    cover: {
      background: "linear-gradient(160deg, #25222c 0%, #64586e 50%, #d9b783 100%)",
      accent: "#f3e4c8",
      text: "#fffdf8",
    },
  },
  {
    id: "book-woman-of-troublesome-creek",
    title: "The Book Woman of Troublesome Creek",
    author: "Kim Michele Richardson",
    price: 7.89,
    format: "Paperback",
    availability: "In Stock",
    copies: 14,
    genres: ["historical fiction", "literary"],
    signals: ["voice-driven", "resilient", "warm", "character-driven", "hopeful"],
    pace: "steady",
    synopsis:
      "A blue-skinned librarian delivers books through Appalachian hills during the Depression.",
    cover: {
      background: "linear-gradient(160deg, #1a2f3b 0%, #44697c 50%, #d4b176 100%)",
      accent: "#f3e3c6",
      text: "#fffdf8",
    },
  },
  {
    id: "nightingale",
    title: "The Nightingale",
    author: "Kristin Hannah",
    price: 8.69,
    format: "Paperback",
    availability: "In Stock",
    copies: 23,
    genres: ["historical fiction", "literary"],
    signals: ["emotionally-rich", "character-driven", "resilient", "immersive", "hopeful"],
    pace: "steady",
    synopsis:
      "Two sisters navigate occupied France in a wartime story of courage and sacrifice.",
    cover: {
      background: "linear-gradient(160deg, #1f2433 0%, #59637b 50%, #dfba82 100%)",
      accent: "#f5e7cb",
      text: "#fffdf8",
    },
  },
  {
    id: "storied-life-aj-fikry",
    title: "The Storied Life of A.J. Fikry",
    author: "Gabrielle Zevin",
    price: 7.89,
    format: "Paperback",
    availability: "In Stock",
    copies: 11,
    genres: ["contemporary fiction", "literary"],
    signals: ["heartfelt", "character-driven", "warm", "reflective", "hopeful"],
    pace: "steady",
    synopsis:
      "A widowed bookseller finds his life opening back up through unexpected visitors and a stolen package.",
    cover: {
      background: "linear-gradient(160deg, #24313d 0%, #5a7280 50%, #dfbb82 100%)",
      accent: "#f4e6cb",
      text: "#fffdf8",
    },
  },
];

export const quickPickIds = [
  "night-circus",
  "project-hail-mary",
  "lessons-in-chemistry",
  "seven-husbands",
  "thursday-murder-club",
  "house-in-cerulean-sea",
  "daisy-jones",
  "circe",
  "remarkably-bright-creatures",
  "silent-patient",
];
